### ISSUE TITLE
Question: BERT implementation

### ISSUE THREAD

**Issue by friederikelbauer** [scikit-learn-contrib/hiclass#67]
Hey everyone!

I am using HiClass in my master thesis and I am comparing different classifiers (flat vs. hierarchical). I am trying to use BERT (pre-trained uncased) with the transformers model. (using this tutorial: https://towardsdatascience.com/text-classification-with-bert-in-pytorch-887965e5820f). Is there a way to implement HiClass with BERT? 

As it has a different structure than others from sklearn (for example no inherent I am unsure how to combine the two packages. Any leads would be helpful! Also other variations of BERT (RoBERTa etc.)

Thankful for any ideas!

**Comment by mirand863** [comment]
Hello @friederikelbauer,

This is a really interesting use case!

I actually discussed something similar with another PhD student during a talk I gave about HiClass a couple of months ago. I believe it is feasible and I found this library that could possibly help you [https://github.com/charles9n/bert-sklearn](https://github.com/charles9n/bert-sklearn). Please, let me know if this helps in your use case and feel free to contact me at fabio.malchermiranda@hpi.de if you want to discuss further.

**Comment by mirand863** [comment]
Hi @friederikelbauer,

Just to keep you updated, I made some progress and now there is support available for all 3 local hierarchical classifiers, i.e., the local classifier per node, per parent node and per level. Also, now you can install the beta version without cloning the repository with `pip install hiclass==4.2.8b1`.

However, the documentation example was not possible yet since bert-sklearn is not available in the python package index. I opened a new issue in their repository and will try to add it myself next week if I get no response from the developers.

Please, let me know if you run into any issues with the beta version.

**Comment by sciencecw** [comment]
Hi,

I wonder how this adaptation deals with memory usage. It seems that a deep-copy is done for every layer/ node. BERT barely fits in most computing instances. It seems that this would crash any kernel pretty quickly, not to mention the need to train the model. That being said, I have not got around to test this out yet

**Comment by mirand863** [comment]
Hi @sciencecw,

You are absolutely right, it does make a deep copy of the model. However, we need to finetune the bert model for each node/level/parent node individually, otherwise it would become a flat classifier. Friederike tried this and I think she ran it successfully, though it did not yield great results for her data.

**Comment by sciencecw** [comment]
> we need to finetune the bert model for each node/level/parent node individually, otherwise it would become a flat classifier. 
Is it possible to have multiple training heads sharing the same body? We don't necessarily need to freeze body weights, just train all classifier simultaneously. Or maybe that is hard to implement given the architecture, given that you rely on `sklearn-BERT`
