### ISSUE TITLE
Compatibility with python 3.10

### ISSUE THREAD

**Issue by arthurtobler** [scikit-learn-contrib/hiclass#85]
**Is your feature request related to a problem? Please describe.**
This library is great but not compatible with python 3.10, which is commonly used now.

**Describe the solution you'd like**
Make the library support python 3.10.

**Describe alternatives you've considered**
Downgrade client libraries to 3.9.

**Additional context**
Could consider 3.11 as well :)

Thanks!

**Comment by mirand863** [comment]
Hi @arthurtobler,

Thank you for the suggestion!

The version was previously strict because one of the dependencies, Ray, was incompatible with python > 3.9. However, this dependency is now optional and I do not see a reason for HiClass not to be compatible with the latest versions. I will assess if this is an easy update and let you know.

Kind regards,
Fabio

**Comment by mirand863** [comment]
@arthurtobler,

Ray now supports Python 3.10, so I did not have to change anything in the pipeline and it was an easy fix. However, Python 3.11 is not supported yet. I will see if I can update the CI/CD in order not to rely on Ray and bypass this issue.

All my tests passed, but please let me know if you find any issues when using Python 3.10.

Kind regards,
Fabio

**Comment by arthurtobler** [comment]
Awesome thanks for the very quick support Fabio!
